const dropdownData = {
  "Mobiles & Tablets": [
    "Smartphones",
    "OnePlus Nord CE3 Lite @ ₹16049*",
    "Samsung M15 @ ₹11999*",
    "Smartwatches",
    "Apple",
    "Samsung",
    "Fireboltt",
    "Noise",
    "Boat",
    "Accessories",
    "Tablet Accessories",
    "Mobile Accessories",
    "Mobile Grips & Stands",
    "Car Mobile Holders",
    "Memory Cards",
    "Cables & Cords",
    "Chargers & Adapters",
    "Headphones & Headsets",
    "Tablets & eReaders",
    "Every Day use Tablets below 15000",
    "Premium Tablets, Above 15001",
    "Power Banks",
    "eSlates",
    "AI Learning Robots",
  ],
  Televisions: [
    "Televisions",
    "Smart TVs",
    "32 Inch TVs",
    "43 Inch TVs",
    "55 Inch TVs",
    "Android TVs",
    "Gaming",
    "Gaming Consoles",
    "Gaming Accessories",
    "Gaming Titles",
    "Gaming Controllers",
    "Projectors",
    "Streaming Devices",
    "Reconnect Disney | Marvel Audio Collection",
    "TV & Audio Accessories",
    "Virtual Reality Headsets",
    "Stabilizers & Surge Protectors",
  ],
  Audio: [
    "Headphones & Headsets",
    "True Wireless",
    "Bluetooth Neckbands",
    "Earphones",
    "Bluetooth Headphones",
    "Gaming Headset",
    "Wired Headphones",
    "Speakers & Soundbars",
    "Bluetooth Speakers",
    "Smart Speakers",
    "Home Theatre Systems",
    "Specialty Speakers",
    "Soundbars",
    "Party Speakers",
    "Multimedia Speakers",
    "Musical Instruments",
    "Guitars and Ukuleles",
    "Microphones",
    "Musical Keyboards",
  ],
  "Home Appliances": [
    "Air Conditioners",
    "Split Air Conditioners",
    "Window Air Conditioners",
    "Smart Air Conditioners",
    "Energy Efficient Air Conditioners",
    "1 ton Air Conditioners",
    "1.5 ton Air Conditioners",
    "5 star Air Conditioners",
    "Air Coolers",
    "Air Purifiers",
    "Washing Machines",
    "Fully Automatic Front Load",
    "Fully Automatic Top Load",
    "Semi-Automatic Top Load",
    "Refrigerators",
    "Single Door",
    "Double Door",
    "Side by Side Refrigerators",
    "Convertible",
    "Vacuum Cleaners",
    "Robotic Vacuum Cleaners",
    "Radiators",
    "Dishwashers",
    "Fans",
    "Cloth Dryers",
    "Geysers",
    "Room Heaters",
  ],
  Computers: [
    "Laptops",
    "Basic use laptops",
    "Student Laptops",
    "Thin and light Laptops",
    "Multi-Tasking Laptops",
    "Gaming Laptops",
    "Content creator Laptops",
    "Computer Monitors",
    "Desktops & All-In-Ones",
    "Bluetooth & WiFi Speakers",
    "Internet Connectivity Devices",
    "Routers",
    "WiFi Range Extenders",
    "Wireless USB Adapters",
    "Printers & Inks",
    "Printers",
    "Toners & Ink Cartridges",
    "Data Storage Devices",
    "Memory Cards",
    "Pen Drives & OTG Drives",
    "Hard Disks & SSD",
    "Computer Accessories",
    "Upto 72% Off, Only on Reliancedigital.in",
    "Computer Networking Cables",
    "Laptop Chargers & Adaptor",
    "Laptop Batteries",
    "Hubs & Docks",
    "Laptop Bags & Sleeves",
    "Laptop Cooling Pad",
    "Laptop Screen Protectors",
    "Laptop Tables & Stands",
    "Mouse Pads",
    "Input Devices",
    "Keyboards",
    "Computer Mouse",
    "Stylus Pens",
  ],
  Cameras: [
    "DSLR Cameras",
    "Mirrorless Cameras",
    "Point & Shoot Cameras",
    "ProSumer Cameras",
    "Action Cameras",
    "Photo Storage Devices",
    "Memory Cards",
    "Pen Drives",
    "Binoculars",
    "Camera Lens",
    "Digital Camera Accessories",
    "Camera Batteries & Chargers",
    "Camera bags & cases",
    "Tripods & Monopods",
    "Action Camera Accessories",
  ],
  "Kitchen Appliances": [
    "Mixers",
    "2 Jar",
    "3 Jar",
    "4 Jar",
    "Water Purifiers",
    "Electric Kettle",
    "Microwaves Oven",
    "Convection",
    "Solo & Grill",
    "OTG",
    "Air Fryer",
    "Food Processor",
    "Cooktops",
    "1 Burner",
    "2 Burner",
    "3 Burner",
    "4 Burner",
    "Induction Cooktops",
    "Rice Cooker",
    "Hobs",
    "Hoods/Chimneys",
    "Cookware",
    "Juicer",
    "1 Jar",
    "2 Jar",
    "3 Jar",
    "4+ Jar",
    "Hand Blender",
    "Hand Mixer",
    "Wet Grinder",
    "Coffee/Tea Makers",
    "Pop up Toasters",
    "Sandwich Makers",
    "Choppers",
    "Specialty Appliances",
    "Electric Kettles",
    "Water Dispensers",
    "Flour Mills",
  ],
  "Personal Care": [
    "Shavers & Trimmers",
    "Epilators",
    "Hair Dryers & Stylers",
    "Weighing Scales",
    "Irons",
    "Hygiene & Personal Care",
    "Digital Thermometers",
    "Massagers",
    "Misc. Care Devices",
    "Garment Steamers",
  ],
  Accessories: [
    "Bags, Cases & Sleeves",
    "Smart Devices",
    "Smart Plugs",
    "Smart Cameras",
    "Smart Sensors",
    "Smart Lights",
    "Smart Speakers",
    "Batteries",
    "Power Banks",
    "Cables & Cords",
    "Chargers & Adapters",
    "Bluetooth & WiFi Speakers",
    "Reconnect Disney | Marvel Accessories",
    "Data Storage Devices",
    "Memory Cards",
    "Pen Drives & OTG Drives",
    "Hard Disks & SSD",
    "Mounts & Stands",
    "Air Conditioner Stands",
    "Car Mobile Holders",
    "Mobile Grips & Stands",
    "Surge Protectors",
    "Webcams",
    "Headphones & Headsets",
    "Cleaners & Protectors",
    "Computer Mouse",
    "Keyboards",
    "Indoor Lighting",
    "Office Electronics",
    "Laminators",
    "Tyre Inflators",
    "Routers",
    "Screen Guards & Protectors",
    "Power Strips & Extension Cords",
    "Stabilizers",
  ],
};

export default dropdownData;
